version: '3.8'
services:

  backend:
    build: /home/rafael/mestrado/IACD/multi-container-app/backend
    ports:
     - 80:80
    depends_on:
     - 'mongodb'
    volumes:
      - log:/app/logs
    stdin_open: true # Inicializa o container em modo interativo
    tty: true # Abrir o terminal no container

  frontend:
    image: frontend:1.1
    build: /home/rafael/mestrado/IACD/multi-container-app/frontend
    ports:
      - 3000:3000
    depends_on:
      - backend

  mongodb:
    image: mongo:6.0
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
  log:

